pipeline {
    agent any

    tools {
        nodejs 'NodeJS-18'
    }

    environment {
        AWS_DEFAULT_REGION = 'ap-south-1'
        S3_BUCKET = 'daivik-portfolio-website'
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timestamps()
        timeout(time: 20, unit: 'MINUTES')
    }

    stages {

        stage('Checkout') {
            steps {
                echo '📥 Checking out source code...'
                checkout scm
            }
        }

        stage('Verify NodeJS') {
            steps {
                echo '⚙️ Verifying Node.js installation...'

                sh '''
                    node --version
                    npm --version
                '''
            }
        }

        stage('Run Ansible Setup') {
            steps {

                echo '⚙️ Running Ansible automation setup...'

                sh '''
                    cd ansible
                    sudo ansible-playbook -i inventory.ini setup.yml
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                echo '📦 Installing project dependencies...'

                sh '''
                    npm install
                '''
            }
        }

        stage('Build Project') {
            steps {
                echo '🔨 Building Vite application...'

                sh '''
                    npm run build
                '''
            }
        }

        stage('Verify Build Files') {
            steps {
                echo '📂 Checking dist folder...'

                sh '''
                    ls -la
                    ls -la dist/
                '''
            }
        }

        stage('Deploy to AWS S3') {
            steps {

                echo '☁️ Deploying website to AWS S3...'

                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-credentials',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {

                    sh '''
                        export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

                        aws s3 sync dist/ s3://${S3_BUCKET} --delete
                    '''
                }
            }
        }
    }

    post {

        success {
            echo '✅ Deployment Successful!'
        }

        failure {
            echo '❌ Pipeline Failed!'
        }

        always {
            echo '🧹 Cleaning workspace...'
            cleanWs()
        }
    }
}