---
- hosts: local

  tasks:

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install AWS CLI
      apt:
        name: awscli
        state: present

    - name: Install NodeJS
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present
