---
- hosts: local

  tasks:

    - name: Verify Docker installation
      command: docker --version
      register: docker_output

    - name: Show Docker version
      debug:
        var: docker_output.stdout

    - name: Verify NodeJS installation
      command: node --version
      register: node_output

    - name: Show NodeJS version
      debug:
        var: node_output.stdout

    - name: Verify AWS CLI installation
      command: aws --version
      register: aws_output

    - name: Show AWS CLI version
      debug:
        var: aws_output.stdout